version: '3.3'
services:
   db:
     image: postgres:latest
     environment:
       - POSTGRES_PASSWORD=123
       - POSTGRES_USER=postgres
       - POSTGRES_DB=test
     restart: always
     ports:
       - "5432:5432"

   roadmap:
     image: tarmogoyf/roadmap:latest
     links:
        - db
     environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/postgres
     ports:
       - "8080:8080"

   pgadmin:
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_PASSWORD: "123"
       PGADMIN_DEFAULT_EMAIL: "qwertygoog@gmail.com"
     ports: ["80:80"]
     depends_on:
        - db