name: codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./lib.c.gcov
          token: ${{ secrets.codecov }}
